// Generated from design tokens - DO NOT EDIT DIRECTLY
// Last generated: 2025-07-08T14:57:46.676Z

export const primitiveColors = {
  "blue-400": "var(--color-blue-400)",
  "blue-500": "var(--color-blue-500)",
  "blue-900": "var(--color-blue-900)",
  "blue-500-10": "var(--color-blue-500-10)",
  "pink-200": "var(--color-pink-200)",
  "pink-400": "var(--color-pink-400)",
  "pink-600": "var(--color-pink-600)",
  "pink-700": "var(--color-pink-700)",
  "brown-500": "var(--color-brown-500)",
  "brown-800": "var(--color-brown-800)",
  "brown-900": "var(--color-brown-900)",
  "neutral-100": "var(--color-neutral-100)",
  "neutral-200": "var(--color-neutral-200)",
  "neutral-300": "var(--color-neutral-300)",
  "neutral-400": "var(--color-neutral-400)",
  "neutral-500": "var(--color-neutral-500)",
  "neutral-600": "var(--color-neutral-600)",
  "neutral-700": "var(--color-neutral-700)",
  "neutral-800": "var(--color-neutral-800)",
  "neutral-900": "var(--color-neutral-900)",
  "neutral-black": "var(--color-neutral-black)",
  "neutral-black-10": "var(--color-neutral-black-10)",
  "neutral-white": "var(--color-neutral-white)",
  "neutral-white-30": "var(--color-neutral-white-30)"
};
export const semanticColors = {
  "border-default": "var(--color-border-default)",
  "border-brand": "var(--color-border-brand)",
  "border-accent-gray": "var(--color-border-accent-gray)",
  "border-accent-gray-subtle": "var(--color-border-accent-gray-subtle)",
  "border-disabled": "var(--color-border-disabled)",
  "border-warning": "var(--color-border-warning)",
  "text-default": "var(--color-text-default)",
  "text-subtle": "var(--color-text-subtle)",
  "text-brand": "var(--color-text-brand)",
  "text-brand-subtle": "var(--color-text-brand-subtle)",
  "text-accent-brown": "var(--color-text-accent-brown)",
  "text-accent-brown-subtle": "var(--color-text-accent-brown-subtle)",
  "text-accent-pink": "var(--color-text-accent-pink)",
  "text-disabled": "var(--color-text-disabled)",
  "text-inverse": "var(--color-text-inverse)",
  "text-warning": "var(--color-text-warning)",
  "text-warning-inverse": "var(--color-text-warning-inverse)",
  "background-default": "var(--color-background-default)",
  "background-dark": "var(--color-background-dark)",
  "background-dark-subtle": "var(--color-background-dark-subtle)",
  "background-brand": "var(--color-background-brand)",
  "background-brand-subtle": "var(--color-background-brand-subtle)",
  "background-brand-subtlest": "var(--color-background-brand-subtlest)",
  "background-accent-gray": "var(--color-background-accent-gray)",
  "background-accent-gray-subtle": "var(--color-background-accent-gray-subtle)",
  "background-accent-brown": "var(--color-background-accent-brown)",
  "background-accent-pink": "var(--color-background-accent-pink)",
  "background-accent-pink-subtle": "var(--color-background-accent-pink-subtle)",
  "background-accent-pink-subtlest": "var(--color-background-accent-pink-subtlest)",
  "background-disabled": "var(--color-background-disabled)",
  "icons-default": "var(--color-icons-default)",
  "icons-gray": "var(--color-icons-gray)",
  "icons-brand": "var(--color-icons-brand)",
  "icons-warning": "var(--color-icons-warning)",
  "icons-inverse": "var(--color-icons-inverse)",
  "shadow-default": "var(--color-shadow-default)"
};
export const componentColors = {
  "form-background-input-field": "var(--color-form-background-input-field-default)",
  "form-background-checkbox": "var(--color-form-background-checkbox-default)",
  "form-border-input-field": "var(--color-form-border-input-field-default)",
  "form-border-checkbox": "var(--color-form-border-checkbox-default)",
  "button-background-primary": "var(--color-button-background-primary-default)",
  "button-background-dark": "var(--color-button-background-dark-default)",
  "button-background-secondary": "var(--color-button-background-secondary-default)",
  "button-background-pill": "var(--color-button-background-pill-default)",
  "button-border-secondary": "var(--color-button-border-secondary-default)",
  "button-border-pill": "var(--color-button-border-pill-default)",
  "button-icon-primary": "var(--color-button-icon-primary-default)",
  "button-icon-secondary": "var(--color-button-icon-secondary-default)",
  "button-icon-pill": "var(--color-button-icon-pill-default)",
  "button-text-primary": "var(--color-button-text-primary-default)",
  "button-text-dark": "var(--color-button-text-dark-default)",
  "button-text-secondary": "var(--color-button-text-secondary-default)",
  "button-text-ghost": "var(--color-button-text-ghost-default)",
  "button-text-pill": "var(--color-button-text-pill-default)",
  "link-text-default": "var(--color-link-text-default-default)",
  "link-text-brown": "var(--color-link-text-brown-default)",
  "form-background-input-field-hover": "var(--color-form-background-input-field-hover)",
  "form-background-checkbox-hover": "var(--color-form-background-checkbox-hover)",
  "form-border-input-field-hover": "var(--color-form-border-input-field-hover)",
  "form-border-checkbox-hover": "var(--color-form-border-checkbox-hover)",
  "button-background-primary-hover": "var(--color-button-background-primary-hover)",
  "button-background-dark-hover": "var(--color-button-background-dark-hover)",
  "button-background-secondary-hover": "var(--color-button-background-secondary-hover)",
  "button-background-pill-hover": "var(--color-button-background-pill-hover)",
  "button-border-secondary-hover": "var(--color-button-border-secondary-hover)",
  "button-border-pill-hover": "var(--color-button-border-pill-hover)",
  "button-icon-primary-hover": "var(--color-button-icon-primary-hover)",
  "button-icon-secondary-hover": "var(--color-button-icon-secondary-hover)",
  "button-icon-pill-hover": "var(--color-button-icon-pill-hover)",
  "button-text-primary-hover": "var(--color-button-text-primary-hover)",
  "button-text-dark-hover": "var(--color-button-text-dark-hover)",
  "button-text-secondary-hover": "var(--color-button-text-secondary-hover)",
  "button-text-ghost-hover": "var(--color-button-text-ghost-hover)",
  "button-text-pill-hover": "var(--color-button-text-pill-hover)",
  "link-text-default-hover": "var(--color-link-text-default-hover)",
  "link-text-brown-hover": "var(--color-link-text-brown-hover)",
  "form-background-input-field-active": "var(--color-form-background-input-field-active)",
  "form-background-checkbox-active": "var(--color-form-background-checkbox-active)",
  "form-border-input-field-active": "var(--color-form-border-input-field-active)",
  "form-border-checkbox-active": "var(--color-form-border-checkbox-active)",
  "button-background-primary-active": "var(--color-button-background-primary-active)",
  "button-background-dark-active": "var(--color-button-background-dark-active)",
  "button-background-secondary-active": "var(--color-button-background-secondary-active)",
  "button-background-pill-active": "var(--color-button-background-pill-active)",
  "button-border-secondary-active": "var(--color-button-border-secondary-active)",
  "button-border-pill-active": "var(--color-button-border-pill-active)",
  "button-icon-primary-active": "var(--color-button-icon-primary-active)",
  "button-icon-secondary-active": "var(--color-button-icon-secondary-active)",
  "button-icon-pill-active": "var(--color-button-icon-pill-active)",
  "button-text-primary-active": "var(--color-button-text-primary-active)",
  "button-text-dark-active": "var(--color-button-text-dark-active)",
  "button-text-secondary-active": "var(--color-button-text-secondary-active)",
  "button-text-ghost-active": "var(--color-button-text-ghost-active)",
  "button-text-pill-active": "var(--color-button-text-pill-active)",
  "link-text-default-active": "var(--color-link-text-default-active)",
  "link-text-brown-active": "var(--color-link-text-brown-active)",
  "form-background-input-field-disabled": "var(--color-form-background-input-field-disabled)",
  "form-background-checkbox-disabled": "var(--color-form-background-checkbox-disabled)",
  "form-border-input-field-disabled": "var(--color-form-border-input-field-disabled)",
  "form-border-checkbox-disabled": "var(--color-form-border-checkbox-disabled)",
  "button-background-primary-disabled": "var(--color-button-background-primary-disabled)",
  "button-background-dark-disabled": "var(--color-button-background-dark-disabled)",
  "button-background-secondary-disabled": "var(--color-button-background-secondary-disabled)",
  "button-background-pill-disabled": "var(--color-button-background-pill-disabled)",
  "button-border-secondary-disabled": "var(--color-button-border-secondary-disabled)",
  "button-border-pill-disabled": "var(--color-button-border-pill-disabled)",
  "button-icon-primary-disabled": "var(--color-button-icon-primary-disabled)",
  "button-icon-secondary-disabled": "var(--color-button-icon-secondary-disabled)",
  "button-icon-pill-disabled": "var(--color-button-icon-pill-disabled)",
  "button-text-primary-disabled": "var(--color-button-text-primary-disabled)",
  "button-text-dark-disabled": "var(--color-button-text-dark-disabled)",
  "button-text-secondary-disabled": "var(--color-button-text-secondary-disabled)",
  "button-text-ghost-disabled": "var(--color-button-text-ghost-disabled)",
  "button-text-pill-disabled": "var(--color-button-text-pill-disabled)",
  "link-text-default-disabled": "var(--color-link-text-default-disabled)",
  "link-text-brown-disabled": "var(--color-link-text-brown-disabled)"
};
export const spacing = {
  "0": "var(--spacing-0)",
  "spacing-layout-breakpoints": "var(--spacing-layout-breakpoints)",
  "spacing-layout-columns": "var(--spacing-layout-columns)",
  "spacing-layout-padding": "var(--spacing-layout-padding)",
  "spacing-layout-gutter": "var(--spacing-layout-gutter)",
  "xxs": "var(--spacing-xxs)",
  "xs": "var(--spacing-xs)",
  "s": "var(--spacing-s)",
  "m": "var(--spacing-m)",
  "l": "var(--spacing-l)",
  "xl": "var(--spacing-xl)",
  "xxl": "var(--spacing-xxl)"
};
export const typographyStyles = {
  "article-heading": "var(--article-heading)",
  "article-heading-light": "var(--article-heading-light)",
  "article-heading-alternate": "var(--article-heading-alternate)",
  "article-heading-2": "var(--article-heading-2)",
  "article-heading-2-light": "var(--article-heading-2-light)",
  "article-heading-2-alternate": "var(--article-heading-2-alternate)",
  "article-body": "var(--article-body)",
  "article-type": "var(--article-type)",
  "article-intro": "var(--article-intro)",
  "article-city": "var(--article-city)",
  "article-quote": "var(--article-quote)",
  "article-question": "var(--article-question)",
  "article-drop-cap": "var(--article-drop-cap)",
  "article-drop-cap-alternate": "var(--article-drop-cap-alternate)",
  "body-light": "var(--body-light)",
  "body-regular": "var(--body-regular)",
  "body-bold": "var(--body-bold)",
  "body-uppercase": "var(--body-uppercase)",
  "body-uppercase-bold": "var(--body-uppercase-bold)",
  "body-uppercase-bold-small": "var(--body-uppercase-bold-small)",
  "heading-2": "var(--heading-2)",
  "heading-3": "var(--heading-3)",
  "heading-page": "var(--heading-page)",
  "heading-subheading": "var(--heading-subheading)",
  "heading-uppercase": "var(--heading-uppercase)",
  "meta-light": "var(--meta-light)",
  "meta-regular": "var(--meta-regular)",
  "meta-bold": "var(--meta-bold)"
};
export const fontFamilies = {
  "article-heading": "var(--article-heading-fontFamily)",
  "article-heading-light": "var(--article-heading-light-fontFamily)",
  "article-heading-alternate": "var(--article-heading-alternate-fontFamily)",
  "article-heading-2": "var(--article-heading-2-fontFamily)",
  "article-heading-2-light": "var(--article-heading-2-light-fontFamily)",
  "article-heading-2-alternate": "var(--article-heading-2-alternate-fontFamily)",
  "article-body": "var(--article-body-fontFamily)",
  "article-type": "var(--article-type-fontFamily)",
  "article-intro": "var(--article-intro-fontFamily)",
  "article-city": "var(--article-city-fontFamily)",
  "article-quote": "var(--article-quote-fontFamily)",
  "article-question": "var(--article-question-fontFamily)",
  "article-drop-cap": "var(--article-drop-cap-fontFamily)",
  "article-drop-cap-alternate": "var(--article-drop-cap-alternate-fontFamily)",
  "body-light": "var(--body-light-fontFamily)",
  "body-regular": "var(--body-regular-fontFamily)",
  "body-bold": "var(--body-bold-fontFamily)",
  "body-uppercase": "var(--body-uppercase-fontFamily)",
  "body-uppercase-bold": "var(--body-uppercase-bold-fontFamily)",
  "body-uppercase-bold-small": "var(--body-uppercase-bold-small-fontFamily)",
  "heading-2": "var(--heading-2-fontFamily)",
  "heading-3": "var(--heading-3-fontFamily)",
  "heading-page": "var(--heading-page-fontFamily)",
  "heading-subheading": "var(--heading-subheading-fontFamily)",
  "heading-uppercase": "var(--heading-uppercase-fontFamily)",
  "meta-light": "var(--meta-light-fontFamily)",
  "meta-regular": "var(--meta-regular-fontFamily)",
  "meta-bold": "var(--meta-bold-fontFamily)"
};
export const fontWeights = {
  "article-heading": "var(--article-heading-fontWeight)",
  "article-heading-light": "var(--article-heading-light-fontWeight)",
  "article-heading-alternate": "var(--article-heading-alternate-fontWeight)",
  "article-heading-2": "var(--article-heading-2-fontWeight)",
  "article-heading-2-light": "var(--article-heading-2-light-fontWeight)",
  "article-heading-2-alternate": "var(--article-heading-2-alternate-fontWeight)",
  "article-body": "var(--article-body-fontWeight)",
  "article-type": "var(--article-type-fontWeight)",
  "article-intro": "var(--article-intro-fontWeight)",
  "article-city": "var(--article-city-fontWeight)",
  "article-quote": "var(--article-quote-fontWeight)",
  "article-question": "var(--article-question-fontWeight)",
  "article-drop-cap": "var(--article-drop-cap-fontWeight)",
  "article-drop-cap-alternate": "var(--article-drop-cap-alternate-fontWeight)",
  "body-light": "var(--body-light-fontWeight)",
  "body-regular": "var(--body-regular-fontWeight)",
  "body-bold": "var(--body-bold-fontWeight)",
  "body-uppercase": "var(--body-uppercase-fontWeight)",
  "body-uppercase-bold": "var(--body-uppercase-bold-fontWeight)",
  "body-uppercase-bold-small": "var(--body-uppercase-bold-small-fontWeight)",
  "heading-2": "var(--heading-2-fontWeight)",
  "heading-3": "var(--heading-3-fontWeight)",
  "heading-page": "var(--heading-page-fontWeight)",
  "heading-subheading": "var(--heading-subheading-fontWeight)",
  "heading-uppercase": "var(--heading-uppercase-fontWeight)",
  "meta-light": "var(--meta-light-fontWeight)",
  "meta-regular": "var(--meta-regular-fontWeight)",
  "meta-bold": "var(--meta-bold-fontWeight)"
};
export const fontSizes = {
  "article-heading": "var(--article-heading-fontSize)",
  "article-heading-light": "var(--article-heading-light-fontSize)",
  "article-heading-alternate": "var(--article-heading-alternate-fontSize)",
  "article-heading-2": "var(--article-heading-2-fontSize)",
  "article-heading-2-light": "var(--article-heading-2-light-fontSize)",
  "article-heading-2-alternate": "var(--article-heading-2-alternate-fontSize)",
  "article-body": "var(--article-body-fontSize)",
  "article-type": "var(--article-type-fontSize)",
  "article-intro": "var(--article-intro-fontSize)",
  "article-city": "var(--article-city-fontSize)",
  "article-quote": "var(--article-quote-fontSize)",
  "article-question": "var(--article-question-fontSize)",
  "article-drop-cap": "var(--article-drop-cap-fontSize)",
  "article-drop-cap-alternate": "var(--article-drop-cap-alternate-fontSize)",
  "body-light": "var(--body-light-fontSize)",
  "body-regular": "var(--body-regular-fontSize)",
  "body-bold": "var(--body-bold-fontSize)",
  "body-uppercase": "var(--body-uppercase-fontSize)",
  "body-uppercase-bold": "var(--body-uppercase-bold-fontSize)",
  "body-uppercase-bold-small": "var(--body-uppercase-bold-small-fontSize)",
  "heading-2": "var(--heading-2-fontSize)",
  "heading-3": "var(--heading-3-fontSize)",
  "heading-page": "var(--heading-page-fontSize)",
  "heading-subheading": "var(--heading-subheading-fontSize)",
  "heading-uppercase": "var(--heading-uppercase-fontSize)",
  "meta-light": "var(--meta-light-fontSize)",
  "meta-regular": "var(--meta-regular-fontSize)",
  "meta-bold": "var(--meta-bold-fontSize)"
};
export const lineHeights = {
  "article-heading": "var(--article-heading-lineHeight)",
  "article-heading-light": "var(--article-heading-light-lineHeight)",
  "article-heading-alternate": "var(--article-heading-alternate-lineHeight)",
  "article-heading-2": "var(--article-heading-2-lineHeight)",
  "article-heading-2-light": "var(--article-heading-2-light-lineHeight)",
  "article-heading-2-alternate": "var(--article-heading-2-alternate-lineHeight)",
  "article-body": "var(--article-body-lineHeight)",
  "article-type": "var(--article-type-lineHeight)",
  "article-intro": "var(--article-intro-lineHeight)",
  "article-city": "var(--article-city-lineHeight)",
  "article-quote": "var(--article-quote-lineHeight)",
  "article-question": "var(--article-question-lineHeight)",
  "article-drop-cap": "var(--article-drop-cap-lineHeight)",
  "article-drop-cap-alternate": "var(--article-drop-cap-alternate-lineHeight)",
  "body-light": "var(--body-light-lineHeight)",
  "body-regular": "var(--body-regular-lineHeight)",
  "body-bold": "var(--body-bold-lineHeight)",
  "body-uppercase": "var(--body-uppercase-lineHeight)",
  "body-uppercase-bold": "var(--body-uppercase-bold-lineHeight)",
  "body-uppercase-bold-small": "var(--body-uppercase-bold-small-lineHeight)",
  "heading-2": "var(--heading-2-lineHeight)",
  "heading-3": "var(--heading-3-lineHeight)",
  "heading-page": "var(--heading-page-lineHeight)",
  "heading-subheading": "var(--heading-subheading-lineHeight)",
  "heading-uppercase": "var(--heading-uppercase-lineHeight)",
  "meta-light": "var(--meta-light-lineHeight)",
  "meta-regular": "var(--meta-regular-lineHeight)",
  "meta-bold": "var(--meta-bold-lineHeight)"
};
export const letterSpacings = {
  "article-heading": "var(--article-heading-letterSpacing)",
  "article-heading-light": "var(--article-heading-light-letterSpacing)",
  "article-heading-alternate": "var(--article-heading-alternate-letterSpacing)",
  "article-heading-2": "var(--article-heading-2-letterSpacing)",
  "article-heading-2-light": "var(--article-heading-2-light-letterSpacing)",
  "article-heading-2-alternate": "var(--article-heading-2-alternate-letterSpacing)",
  "article-body": "var(--article-body-letterSpacing)",
  "article-type": "var(--article-type-letterSpacing)",
  "article-intro": "var(--article-intro-letterSpacing)",
  "article-city": "var(--article-city-letterSpacing)",
  "article-quote": "var(--article-quote-letterSpacing)",
  "article-question": "var(--article-question-letterSpacing)",
  "article-drop-cap": "var(--article-drop-cap-letterSpacing)",
  "article-drop-cap-alternate": "var(--article-drop-cap-alternate-letterSpacing)",
  "body-light": "var(--body-light-letterSpacing)",
  "body-regular": "var(--body-regular-letterSpacing)",
  "body-bold": "var(--body-bold-letterSpacing)",
  "body-uppercase": "var(--body-uppercase-letterSpacing)",
  "body-uppercase-bold": "var(--body-uppercase-bold-letterSpacing)",
  "body-uppercase-bold-small": "var(--body-uppercase-bold-small-letterSpacing)",
  "heading-2": "var(--heading-2-letterSpacing)",
  "heading-3": "var(--heading-3-letterSpacing)",
  "heading-page": "var(--heading-page-letterSpacing)",
  "heading-subheading": "var(--heading-subheading-letterSpacing)",
  "heading-uppercase": "var(--heading-uppercase-letterSpacing)",
  "meta-light": "var(--meta-light-letterSpacing)",
  "meta-regular": "var(--meta-regular-letterSpacing)",
  "meta-bold": "var(--meta-bold-letterSpacing)"
};
export const primitiveFontFamilies = {
  "gulliver": "var(--font-family-gulliver)",
  "fira-sans": "var(--font-family-fira-sans)",
  "montserrat": "var(--font-family-montserrat)",
  "abril-fatface": "var(--font-family-abril-fatface)",
  "gulliver-semibold": "var(--font-family-gulliver-semibold)"
};
export const primitiveFontSizes = {
  "12": "var(--font-size-12)",
  "14": "var(--font-size-14)",
  "15": "var(--font-size-15)",
  "16": "var(--font-size-16)",
  "17": "var(--font-size-17)",
  "18": "var(--font-size-18)",
  "20": "var(--font-size-20)",
  "22": "var(--font-size-22)",
  "24": "var(--font-size-24)",
  "26": "var(--font-size-26)",
  "28": "var(--font-size-28)",
  "30": "var(--font-size-30)",
  "32": "var(--font-size-32)",
  "36": "var(--font-size-36)",
  "40": "var(--font-size-40)",
  "48": "var(--font-size-48)",
  "88": "var(--font-size-88)",
  "96": "var(--font-size-96)"
};
export const primitiveFontWeights = {
  "bold": "var(--font-weight-bold)",
  "semibold": "var(--font-weight-semibold)",
  "regular": "var(--font-weight-regular)",
  "light": "var(--font-weight-light)"
};
export const primitiveLetterSpacings = {
  "0": "var(--letter-spacing-0)",
  "s": "var(--letter-spacing-s)",
  "m": "var(--letter-spacing-m)",
  "l": "var(--letter-spacing-l)"
};
export const primitiveBorderWidths = {
  "0": "var(--border-width-0)",
  "s": "var(--border-width-s)"
};
export const primitiveBorderRadius = {
  "0": "var(--border-radius-0)",
  "xl": "var(--border-radius-xl)"
};
export const semanticBorderRadius = {
  "pill": "var(--border-radius-pill)"
};
export const primitiveBoxShadows = {
  "s": "var(--box-shadow-s)",
  "m": "var(--box-shadow-m)",
  "l": "var(--box-shadow-l)"
};